version: '3.1'

services:
  twoandahalfmenapp:
    image: twoandahalfmenapp
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000

  db:
    image: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: twoandahalfmen-db

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    links:
      - db
    environment:
      - PMA_ARBITRARY=1
